name: Testing Generic

on:
  workflow_dispatch:
    
jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os: [ 'macos-13']
        
    runs-on: ${{ matrix.os }}

    steps:
      - name: Temp
        run: | 
          pip3 --version
          python3 --version
          echo "----------------"
          which python3
          which pip3
          python3 -m pip install --upgrade pip
          pip3 --version
          echo "----------------"
          pip --version
          python --version
